name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo -e "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}\nDATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          yarn
          yarn audit
      - name: Lint (code analysis)
        run: yarn lint
      - name: Test (unit and integration testing)
        run: yarn test
      - name: Serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}